grumpyhome/grumpy

- grumpy-runtime-src/third_party/stdlib/json/decoder.py
``` python
a = (1,)
c, = a
print(type(c))
```
There is something wrong behavior on the tuple assignment of grumpy.
This PR does not fix the essential problem but fix to use json library.
Updates: #3
> stdlib.json.decoder: Hot fix for json decoder

- grumpy-tools-src/grumpy_tools/vendor/pythonparser/source.py
__exception__ (lowercase 'e') is an undefined name in this context while __Exception__ (uppercase 'e') is the superclass.
[flake8](http://flake8.pycqa.org) testing of https://github.com/grumpyhome/grumpy on Python 2.7.14
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./grumpy_tools/vendor/pythonparser/source.py:259:9: F821 undefined name 'exception'
exception.__init__(self, "Ranges %s and %s overlap" % (repr(first), repr(second)))
^
1     F821 undefined name 'exception'
1
```
> Undefined name: exception --> Exception

- grumpy-runtime-src/runtime/core.go
- grumpy-runtime-src/runtime/module.go
- grumpy-runtime-src/runtime/module_test.go
- grumpy-tools-src/grumpy_tools/compiler/imputil.py
- grumpy-tools-src/grumpy_tools/compiler/imputil_test.py
- grumpy-tools-src/grumpy_tools/compiler/stmt.py
- grumpy-tools-src/grumpy_tools/compiler/stmt_test.py
- grumpy-tools-src/grumpy_tools/grumpc.py
- grumpy-tools-src/grumpy_tools/pydeps.py
Fixes #109.
Importing `from time import wrongmember` raises ImportError as CPython, not AttributeError.
Importing `import wrongmodule` raises ImportError on runtime as CPython, not grumpy_tools.compiler.util.ImportError on compile time
> Fixes #109: Imports raising AttributeError instead of ImportError

- grumpy-runtime-src/runtime/builtin_types.go
- grumpy-runtime-src/runtime/callableiter.go
- grumpy-runtime-src/runtime/callableiter_test.go
- grumpy-runtime-src/runtime/core.go
- grumpy-runtime-src/runtime/core_test.go
To support the `sentinel` variant of `iter`, a new iterator type had to be added: `callableIterator`. I'm not completely happy that I had to put it in its own file (callableiter.go), but I did not find a suitable place for it (core.go was a candidate, but it does not really define types).
> Added support for iter(f, sentinel)

- grumpy-runtime-src/Makefile
As said in https://github.com/golang/lint/issues/415, `golint` should be installed from `golang.org/x/lint/golint` instead of `github.com/golang/lint/golint`
This PR fixes #114
> [Fix #114] `go get golint` is failing

- grumpy-runtime-src/runtime/dict.go
- grumpy-runtime-src/runtime/dict_test.go
- grumpy-runtime-src/runtime/set.go
- grumpy-runtime-src/testing/builtin_test.py
- grumpy-runtime-src/testing/dict_test.py
Implements order-preserving dictionary a-la python 3.7.
- Switch entry storage from `[]*dictEntry` to `[]dictEntry`, store entries in order and use index hash table for hash lookup.
Memory ordering now relies:
-- table is stored last after resize
-- `index` is written after new entry is written, and `fill` incremented then
- Abuse 'pointer to huge array' trick to simulate pointer arithmetic and store only one pointers instead of slices. It saves allocations a bit. But probably, it will reduce possibility of compiler optimization. Currently, there is no noticeable difference except allocations 
- Do not allocate dictTable for empty dict at all. It has huge impact on creation of StopIteration exception.
Note that nil checks are free, because compiler inserted hidden nil checks could be …
> Implement ordered dictionary

- grumpy-tools-src/grumpy_tools/compiler/stmt.py
On the same spirit of #118, simple having a code that have `exec` on it does not mean that it will be called. Should compile and maybe raise a `NotImplementedError` on runtime, if called.
```python
try:
from math import sum
except ImportError:
exec '2+2'
```
and:
```bash
$ grumpy -c 'exec "2+2"'
Traceback (most recent call last):
File "/Users/alanjds/src/git/grumpy/grumpy-tools-src/__main__.py", line 1, in <module>
NotImplementedError: exec is not available on Grumpy. Maybe never be.
```
> Allow code that uses `exec` to fail on run time instead of compile time

- grumpy-tools-src/grumpy_tools/compiler/stmt.py
- grumpy-tools-src/grumpy_tools/compiler/stmt_test.py
Fixes `with` statement having more than one target
```bash
$ grumpy -v debug -m zipfile
info: GOPATH: /Users/alanjds/go:/Users/alanjds/src/git/grumpy/grumpy-runtime-src/grumpy_runtime/data/gopath
info: __main__ pycache folder: /var/folders/ch/j0__hzj563l55q2pz_c249km0000gn/T/tmpApl332__pycache__
debug: Should transpile '__main__'
debug: Dependencies file regenerated
Traceback (most recent call last):
...
File "/Users/alanjds/src/git/grumpy/grumpy-tools-src/grumpy_tools/compiler/stmt.py", line 421, in visit_With
assert len(node.items) == 1, 'multiple items in a with not yet supported'
AssertionError: multiple items in a with not yet supported
```
This is needed by `zipfile` and `pip` at least
> Fix multiple `with` statement

- grumpy-tools-src/grumpy_tools/compiler/imputil.py
This is needed when a CPython stdlib module tries to import another. E.g. `zipfile` imports `os`:
Should be provided the Grumpy `os` module but there is an `os.py` on the same folder of stdlib `zipfile.py`.
> Grumpy' stdlib have preference over CPython' stdlib

- grumpy-tools-src/grumpy_tools/grumpc.py
- grumpy-tools-src/grumpy_tools/grumprun.py
- grumpy-tools-src/grumpy_tools/pep_support/pep3147pycache.py
Fixes #124
The module `struct` still does not compile, but is because `_struct` is a C module, not because its name is not compatible with Grumpy way to deal with Go.
> Go keywords on Python module names are changed to not clash

- grumpy-tools-src/grumpy_tools/cli.py
- grumpy-tools-src/grumpy_tools/compiler/imputil.py
- grumpy-tools-src/grumpy_tools/grumpc.py
- grumpy-tools-src/grumpy_tools/grumprun.py
On Python the circular imports are usually handled by issuing it inside the function needing it.
module_A.function_one needs module_B.function_one, but module_B.method_two can need module_A.helper_two, that is evaluated on run time. This makes the A -> B -> A work by letting the B -> be lazy.
However Go does not allow it. The solution was to bubble up all the imports to the main.go, as it was before the PEP-3147 (`__pycache__`) support got added.
This is needed, e.g., by zipfile.py that imports shutil.py that conditionally imports zipfile.py
> Fix circular imports (zipfile.py)

- grumpy-tools-src/grumpy_tools/cli.py
- grumpy-tools-src/grumpy_tools/grumprun.py
Delve debug on `grumpy run --go-action debug ... `
And `go build` instead of `run` on `grumpy run --go-action build`
Probable is a better CLI API to have separate commands for "run" and
"build", but is more code on an already clumsy function.
Should be refactored later.
And TODO: Add docs about needing to install Delve (`dlv`) Go debugger.
> Delve debug on `grumpy run --go-action debug ... `

- grumpy-runtime-src/runtime/function.go
- grumpy-runtime-src/runtime/method.go
- grumpy-runtime-src/runtime/module.go
- grumpy-tools-src/grumpy_tools/compiler/stmt.py
- grumpy-tools-src/grumpy_tools/compiler/stmt_test.py
Docstrings are needed for some stdlib modules to be importable. E.g. `struct.py` imports `__doc__` from `_struct.py`, but there the `__doc__` is implicitly assumed as the 1st string statement of the file.
The actual PR assumes every module, class and function/method to start with an empty (`None`) `__doc__`. The AST visitor is told to take the 1st `Str` statement and inject an `__doc__ = <value:str>` "Assign" node.
It works very well for modules and module-level functions, but not for methods. Should be refactored later, maybe to show the `__doc__` as a slot instead of a member of `__dict__` of such function/method
> Pep 257: docstrings

- grumpy-runtime-src/runtime/str.go
- grumpy-runtime-src/testing/str_test.py
Its important for example for: 
`print(datetime.now())`
And may be checked in this way:
`"%c" % 107 # gives letter 'k'`
and this:
`"%c" % "k" # gives letter 'k' too`
> add c variant for old str formatting

- grumpy-tools-src/grumpy_tools/grumprun.py
It costs some "user" time. Maybe not needed on "fast" optimized compilations.
But the resulting traceback includes the lines of the full stack, but only if the file is available. As the `-c` and `$ grumpy "mycode; goees; here"` ways does not produce a file, it does not print the traceback of the 1st level.
This should be considered a bug, to be fixed on a new PR
> Full traceback needs some extra modules

- grumpy-runtime-src/Makefile
"find: compiler.." message is not showing now. I think this https://github.com/grumpyhome/grumpy/issues/6 may be closed.
> remove compiler search

- .travis.yml
Seems travis ci have issues with macOS and brew, and these PRs is blocked by this:
- https://github.com/grumpyhome/grumpy/pull/144
- https://github.com/grumpyhome/grumpy/pull/145
This PR is a workaround for do not block by it before traivs's stuff fixed it, from: https://travis-ci.community/t/syntax-error-unexpected-keyword-rescue-expecting-keyword-end-in-homebrew/5623/2
> Fix travis ci with osx build

- .travis.yml
Because Python 3.8 is due in 10 days.
> Travis CI:  Upgrade to Python 3.8

- grumpy-runtime-src/testing/list_test.py
Fixes #67 
**Changes:**
* Remove AssertionError
* Assert False and return the Exception string that should have occurred from the previous line
As of now made the changes only to `list_test.py`. Let me know if this is good or any more changes are required.
> fixes issue #67 - replace AssertionError with False and respective error string

- grumpy-runtime-src/MANIFEST.in
- grumpy-runtime-src/Makefile
- grumpy-runtime-src/pyproject.toml
`pip2 install grumpy-runtime` fails with the ERROR
https://github.com/grumpyhome/grumpy/issues/113#issuecomment-521527773
because it relies on `grumpy-tools`.
`grumpy-tools` packages is specified in `setup.py` as a
dependency, and it doesn't work, because for the build process to
succeed, the dependency should already exist at the time `setup.py`
is executed.
The official workaround is `pyproject.toml` from PEP-518
https://github.com/pypa/pip/issues/2381
> Install grumpy-tools before building grumpy-runtime

- README.md
If you'd prefer this setup differently just let me know and I'll re-format to your specifications.
> Added installation steps for Python 2.7 and go 1.10+
